/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct cstr_st;

struct poly1305_context {
    unsigned long long _field1;
    unsigned char _field2[136];
};

struct srp_meth_st;

struct srp_server_lu_st;

struct srp_st {
    int _field1;
    int _field2;
    struct cstr_st *_field3;
    void *_field4;
    void *_field5;
    struct cstr_st *_field6;
    void *_field7;
    void *_field8;
    void *_field9;
    void *_field10;
    void *_field11;
    void *_field12;
    struct cstr_st *_field13;
    struct srp_meth_st *_field14;
    void *_field15;
    void *_field16;
    void *_field17;
    void *_field18;
    struct srp_server_lu_st *_field19;
    struct *_field20;
};

