/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol HAKAccessoryDelegate <NSObject>

@optional
- (void)accessory:(id)arg1 didUpdateService:(id)arg2;
- (void)accessory:(id)arg1 didRemoveService:(id)arg2;
- (void)accessory:(id)arg1 didFailToAddService:(id)arg2 error:(id)arg3;
- (void)accessory:(id)arg1 didAddService:(id)arg2;
@end

