/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData;

@interface HAKChaChaPolyData : NSObject
{
    NSData *_data;
}

@property(copy, nonatomic) NSData *data; // @synthesize data=_data;

@property(readonly, nonatomic) NSData *authTag;
@property(readonly, nonatomic) NSData *encryptedData;
- (id)description;
- (id)initWithData:(id)arg1;

@end

