/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface HAKCurve25519 : NSObject
{
}

+ (id)sharedKeyWithSecretKey:(id)arg1 publicKey:(id)arg2;
+ (id)publicKeyWithSecretKey:(id)arg1;
+ (id)secretKey;

@end

