/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "HAKHTTPMessage.h"

@class HAKIPConnection, NSString, NSURL;

@interface HAKHTTPRequestMessage : HAKHTTPMessage
{
    HAKIPConnection *_connection;
}

@property(readonly, nonatomic) HAKIPConnection *connection; // @synthesize connection=_connection;

@property(readonly, nonatomic) BOOL isComplete;
@property(readonly, nonatomic) BOOL isBodyComplete;
@property(readonly, nonatomic) unsigned long long bodyLength;
@property(readonly, nonatomic) NSURL *url;
@property(readonly, nonatomic) NSString *method;
- (id)description;
- (id)initWithConnection:(id)arg1;

@end

