/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@import Foundation;

#import "NSCopying-Protocol.h"

@interface HAKInstanceIDPool : NSObject <NSCopying>
{
    unsigned long long _currentInstanceID;
}

+ (id)instanceIDPoolWithInstanceID:(unsigned long long)arg1;
+ (id)instanceIDPool;
@property(readonly, nonatomic) unsigned long long currentInstanceID; // @synthesize currentInstanceID=_currentInstanceID;

- (id)instanceID;
- (id)initWithInstanceID:(unsigned long long)arg1;


@end

