/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@import Foundation;

@class  NSString;

@interface HAKKeychainService : NSObject
{
    struct OpaqueSecKeychainRef *_keychain;
    BOOL _authenticationDisabled;
    dispatch_queue_t _workQueue;
}

+ (id)keychainURL;
+ (id)defaultKeychainService;
@property(nonatomic, getter=isAuthenticationDisabled) BOOL authenticationDisabled; // @synthesize authenticationDisabled=_authenticationDisabled;
@property(retain) dispatch_queue_t workQueue; // @synthesize workQueue=_workQueue;

- (void)_executePrivledgedKeychainBlock:(id)arg1;
- (void)_executeKeychainBlock:(id)arg1;
- (int)_unlockWithPassword:(id)arg1;
- (BOOL)unlock;
- (int)_isUnlocked:(char *)arg1;
- (BOOL)isUnlocked;
- (BOOL)_createKeychain;
@property(readonly) struct OpaqueSecKeychainRef *keychain;
- (BOOL)_keychainExists;
@property(retain, nonatomic) NSString *password;
- (int)_getPassword:(id *)arg1;
- (int)_key:(id *)arg1 keyClass:(unsigned long long)arg2 account:(id)arg3 service:(id)arg4;
- (id)keyWithKeyClass:(unsigned long long)arg1 account:(id)arg2 service:(id)arg3;
- (int)_key:(id *)arg1 withKeyRef:(void *)arg2;
- (int)_keys:(id *)arg1 keyClass:(unsigned long long)arg2 account:(id)arg3 service:(id)arg4;
- (id)keysWithKeyClass:(unsigned long long)arg1 account:(id)arg2 service:(id)arg3;
- (int)_removeKey:(id)arg1;
- (BOOL)removeKey:(id)arg1 error:(id *)arg2;
- (int)_addKey:(id)arg1;
- (BOOL)addKey:(id)arg1 error:(id *)arg2;


@end

