/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@import Foundation;

@class HAKMetadata, NSObject<OS_dispatch_queue>;

@interface HAKMetadataService : NSObject
{
    HAKMetadata *_metadata;
    dispatch_queue_t _workQueue;
}

+ (id)defaultMetadataService;
@property(retain, nonatomic) dispatch_queue_t workQueue; // @synthesize workQueue=_workQueue;

@property(retain, nonatomic) HAKMetadata *metadata;


@end

