/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "HAKValueConstraints.h"

@class NSNumber;

@interface HAKNumberConstraints : HAKValueConstraints
{
    NSNumber *_minimumValue;
    NSNumber *_maximumValue;
    NSNumber *_stepValue;
}

@property(copy, nonatomic) NSNumber *stepValue; // @synthesize stepValue=_stepValue;
@property(readonly, copy, nonatomic) NSNumber *maximumValue; // @synthesize maximumValue=_maximumValue;
@property(readonly, copy, nonatomic) NSNumber *minimumValue; // @synthesize minimumValue=_minimumValue;

- (BOOL)validateValue:(id)arg1;

- (id)initWithMinimumValue:(id)arg1 maximumValue:(id)arg2;

- (id)attributes;

@end

