/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "HAKPairingCharacteristic.h"

#import "HAKPairSetupSessionDelegate-Protocol.h"

@class HAKConnection, HAKPairSetupSession,  NSString;

@interface HAKPairSetupCharacteristic : HAKPairingCharacteristic <HAKPairSetupSessionDelegate>
{
    HAKConnection *_currentConnection;
    HAKPairSetupSession *_pairSetupSession;
    dispatch_queue_t_pairSetupQueue;
}

+ (id)pairSetupCharacteristic;
@property(retain, nonatomic) dispatch_queue_tpairSetupQueue; // @synthesize pairSetupQueue=_pairSetupQueue;
@property(retain, nonatomic) HAKPairSetupSession *pairSetupSession; // @synthesize pairSetupSession=_pairSetupSession;
@property(nonatomic) __weak HAKConnection *currentConnection; // @synthesize currentConnection=_currentConnection;

- (void)pairSetupSession:(id)arg1 didAddPairing:(id)arg2;
- (id)handleReadRequest:(id)arg1;
- (id)handleWriteRequest:(id)arg1;
- (id)passwordForPairSetupSession:(id)arg1;
- (id)identifierForPairingSession:(id)arg1;
- (id)initWithType:(id)arg1 properties:(unsigned long long)arg2 format:(unsigned long long)arg3;



@end

