/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "HAKPairingCharacteristic.h"

#import "HAKAddPairingSessionDelegate-Protocol.h"
#import "HAKListPairingsSessionDataSource-Protocol.h"
#import "HAKListPairingsSessionDelegate-Protocol.h"
#import "HAKRemovePairingSessionDelegate-Protocol.h"

@class NSString;

@interface HAKPairingsCharacteristic : HAKPairingCharacteristic <HAKAddPairingSessionDelegate, HAKRemovePairingSessionDelegate, HAKListPairingsSessionDelegate, HAKListPairingsSessionDataSource>
{
}

+ (id)pairingsCharacteristic;
- (id)pairingsForListPairingsSession:(id)arg1;
- (BOOL)controllerIsAdminForListPairingsSession:(id)arg1;
- (BOOL)removePairingSession:(id)arg1 removePairingForIdentifier:(id)arg2;
- (BOOL)controllerIsAdminForRemovePairingSession:(id)arg1;
- (void)addPairingSession:(id)arg1 didAddPairing:(id)arg2;
- (BOOL)controllerIsAdminForAddPairingSession:(id)arg1;
- (id)handleReadRequest:(id)arg1;
- (id)handleWriteRequest:(id)arg1;
- (id)initWithType:(id)arg1 properties:(unsigned long long)arg2 format:(unsigned long long)arg3;



@end

