/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@import Foundation;

@class HAKTransport, NSArray, NSHashTable,  NSString;

@interface HAKPairing : NSObject
{
    NSHashTable *_connections;
    BOOL _admin;
    HAKTransport *_transport;
    NSString *_identifier;
    dispatch_queue_t _workQueue;
}

@property(retain, nonatomic) dispatch_queue_t workQueue; // @synthesize workQueue=_workQueue;
@property(readonly, nonatomic, getter=isAdmin) BOOL admin; // @synthesize admin=_admin;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) __weak HAKTransport *transport; // @synthesize transport=_transport;

- (id)keychainObject;
- (void)_addConnection:(id)arg1;
- (void)addConnection:(id)arg1;
@property(readonly, nonatomic) NSArray *connections;

- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithIdentifier:(id)arg1 admin:(BOOL)arg2;

@end

