/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "HAKPairingSessionDelegate-Protocol.h"

@protocol HAKPairSetupSessionDelegate <HAKPairingSessionDelegate>

@optional
- (void)pairSetupSession:(id)arg1 didAddPairing:(id)arg2;
- (id)passwordForPairSetupSession:(id)arg1;
@end

