/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "HAKPairingSessionDelegate-Protocol.h"

@protocol HAKRemovePairingSessionDelegate <HAKPairingSessionDelegate>
- (BOOL)removePairingSession:(id)arg1 removePairingForIdentifier:(id)arg2;
- (BOOL)controllerIsAdminForRemovePairingSession:(id)arg1;
@end

