/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@import Foundation;

@class NSData;

@interface HAKSecuritySession : NSObject
{
    NSData *_accessoryToControllerKey;
    unsigned long long _accessoryToControllerCount;
    NSData *_controllerToAccessoryKey;
    unsigned long long _controllerToAccessoryCount;
}


- (id)encryptData:(id)arg1;
- (id)initWithSharedSecret:(id)arg1;

@end

