/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@import Foundation;

@interface NSDictionary (Safe)
- (id)_objectForKey:(id)arg1 class:(Class)arg2;
- (id)stringForKey:(id)arg1;
- (id)numberForKey:(id)arg1;
- (id)dictionaryForKey:(id)arg1;
- (id)arrayForKey:(id)arg1;
@end

