/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@import Foundation;

@interface NSError (HAKError)
+ (id)errorWithCode:(long long)arg1 description:(id)arg2 suggestion:(id)arg3;
+ (id)errorWithCode:(long long)arg1 description:(id)arg2;
@end

