/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@import Foundation;

@interface NSFileManager (HAK)
- (id)fileModificationDateForURL:(id)arg1 error:(id *)arg2;
- (id)fileSizeForURL:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
@end

